// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovutsnoyaeewfcwlfgfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92dXRzbm95YWVld2Zjd2xmZ2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzAzNTEsImV4cCI6MjA3MDkwNjM1MX0.mIKAz88IAS9qbEc4fG8wYiyXsGKFsSwp8DGt6kipNgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});